### ISSUE TITLE
Could you add a bill_type attribute to the deal model?

### ISSUE THREAD

**Issue by ekim-mm** [MediaMath/t1-python#103]
A new attribute, 'bill_type', was added to the deals model in Adama a few months ago (adama/lib/Adama/DB/Object/Deal.pm)

It is only readable and writable with a feature flag called 'api.media.deal_bill_type' so the API specs were never modified to reflect this addition. Would you mind adding it to the model? t1-python/terminalone/models/deal.py

It is of enum type with "EXCHANGE" "PUBLISHER" and "NONE" as three options.

Thank you!

**Comment by FodT** [comment]
resolved by #104
