### ISSUE TITLE
Spend Cap Deprecated

### ISSUE THREAD

**Issue by fsargent** [MediaMath/t1-python#109]
https://github.com/MediaMath/t1-python/blob/master/terminalone/models/campaign.py#L150

t1-python still references the old campaigns.spend_cap_enabled field which was deprecated earlier this month. 

Specifically, this line appears to be the main culprit; it looks like t1-python tries to POST a non-existent field to T1, which in turn complains.

**Comment by FodT** [comment]
This code is here to enable the migration assist features introduced to campaigns and strategies in #98 when the pacing was changed (see #97). I agree this code does eventually need to come out, but not just yet.

**Comment by conoverm** [comment]
Any updates on this?

**Comment by FodT** [comment]
@conoverm this was resolved in a recent commit. Haven't cut a release yet, but feel free to use Head right now.

**Comment by conoverm** [comment]
great!

**Comment by conoverm** [comment]
@FodT the migration for the impression_cap is still there though. Is that right?

Spend_cap and impression_cap were changed in the API at the same time as part of the same changes.

https://github.com/MediaMath/t1-python/blob/master/terminalone/models/strategy.py#L131

**Comment by FodT** [comment]
@conoverm yep, it's in place to aid with migrating campaigns created before the switch, which are still in flight.
