### ISSUE TITLE
Migrate Deals to new 'Media' Endpoint

### ISSUE THREAD

**Issue by fsargent** [MediaMath/t1-python#110]
/api/v2.0/deals -> /media/v1.0/deals

/api/v2.0/strategies/:id/supplies -> /api/v2.0/strategies/:id/deals

https://developer.mediamath.com/docs/read/execution_and_management_api/Private_Marketplace_Exchange_PMPE_Setup_New

only for deals (pmp-e) AND NOT supply_sources (exchanges), site_placements (pmp-d) – which remain active under /supplies.

**Comment by conoverm** [comment]
Any updates on this?

**Comment by fsargent** [comment]
We should have an initial implementation of this by end of next week.

**Comment by fsargent** [comment]
#107 Are these related/the same?

**Comment by conoverm** [comment]
nice

**Comment by fsargent** [comment]
This is resolved in: https://github.com/MediaMath/t1-python/tree/v1.6.0 
PR: #122
