### ISSUE TITLE
Enable pickling

### ISSUE THREAD

**Issue by pswaminathan** [MediaMath/t1-python#13]
Add `__getstate__` and `__setstate__` methods to `Entity` to enable pickling.

Unanswered questions:
- What do I do with `requests` sessions?

**Comment by FodT** [comment]
@pswaminathan do you have anything to share on this one?

**Comment by pswaminathan** [comment]
I go back and forth on whether or not I think it's useful. If it is useful, it wouldn't be too difficult to do, but I haven't seen anyone ask for it, nor have I found a concrete place I thought it would be worthwhile. I suppose that's enough of an answer and we should just close this out.
