### ISSUE TITLE
ClientError: 'Cannot handle content type: text/html' on t1.get('strategies', 2021657, child='region')

### ISSUE THREAD

**Issue by robrechtdr** [MediaMath/t1-python#137]
> Ran with version with latest commit https://github.com/robrechtdr/t1-python/commit/294e3be7a8477201cf3ef041e1229e80b04d9c13 (is cloned version, as previously [reported other error](https://github.com/MediaMath/t1-python/issues/131) occurs otherwise)

```
> t1.get('strategies', 2021657, child='region')

Traceback (most recent call last):
  File "/Users/rrouck/.virtualenvs/pi-automation-api-dev/lib/python2.7/site-packages/werkzeug/wsgi.py", line 703, in __next__
    return self._next()
  File "/Users/rrouck/.virtualenvs/pi-automation-api-dev/lib/python2.7/site-packages/werkzeug/wrappers.py", line 81, in _iter_encoded
    for item in iterable:
  File "/Users/rrouck/pi-automation-api/automation_api/runners.py", line 789, in create_targets
    strategy_targeting = t1.get('strategies', strategy_id, child=t1_dimension)
  File "/Users/rrouck/.virtualenvs/pi-automation-api-dev/lib/python2.7/site-packages/terminalone/service.py", line 363, in get
    entities, ent_count = super(T1, self)._get(self._get_service_path(collection), _url, params=_params)
  File "/Users/rrouck/.virtualenvs/pi-automation-api-dev/lib/python2.7/site-packages/terminalone/connection.py", line 187, in _get
    return self._parse_response(response)
  File "/Users/rrouck/.virtualenvs/pi-automation-api-dev/lib/python2.7/site-packages/terminalone/connection.py", line 213, in _parse_response
    raise ClientError('Cannot handle content type: {}'.format(content_type))
ClientError: 'Cannot handle content type: text/html'
```

**Comment by FodT** [comment]
@robrechtdr is this still happening? a content type header of `text/html` should never be returned from adama, I'm wondering if there was a nginx snafu.

**Comment by robrechtdr** [comment]
Looks like it, the endpoint we were running that got stuck on this issue now processed through.

**Comment by robrechtdr** [comment]
Problem is still occurring frequently on consecutive runs (something we need to do) with diff params. Can anyone working on Adama check this?

The corresponding get request uses the following url: `https://t1qa10.mediamath.com/api/v2.0/strategies/2021487/target_dimensions/7`.

**Comment by FodT** [comment]
Ah, this is on qa10? I would ask in the current issues: qa room.

**Comment by robrechtdr** [comment]
Seems to also occur on production.

**Comment by robrechtdr** [comment]
### Failing case:

* returned header:
`{'Date': 'Tue, 28 Feb 2017 14:19:09 GMT', 'Content-Length': '166', 'Content-Type': 'text/html', 'Connection': 'close', 'Server': 'nginx'}`
* returned content:
```
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

vs

### Passing case:

* returned header: 
```
{'Content-Length': '432', 'Access-Control-Allow-Methods': 'GET, HEAD, POST, PUT, DELETE', 'Set-Cookie': 'adama_session=f0a1dad4eb17545425e2a72e0cdda65a1b5c2143; path=/; expires=Thu, 02-
Mar-2017 14:19:08 GMT; HttpOnly', 'Cache-Control': 'no-cache', 'Keep-Alive': 'timeout=360', 'Server': 'Apache/2.2.22 (Debian)', 'X-Framework': 'Adama2', 'Connection': 'keep-alive', 'ETa
g': 'ab7290487fd0868223ef99f74e239c157e01b9df', 'Access-Control-Allow-Credentials': 'true', 'Date': 'Tue, 28 Feb 2017 14:19:08 GMT', 'X-Mashery-Responder': 'prod-j-worker-us-east-1b-112
.mashery.com', 'Access-Control-Allow-Headers': 'X-CSRF-Token, Content-Type', 'Content-Type': 'application/vnd.mediamath.v1+json', 'Expires': 'Tue, 28 Feb 2017 14:19:07 GMT'}
```
* returned content:
 ```
{
   "data" : {
      "include" : [
         {
            "is_targetable" : true,
            "value" : 60231,
            "entity_type" : "target_value",
            "name" : "United States",
            "id" : 251,
            "target_dimension_id" : 7,
            "code" : "us"
         }
      ],
      "enabled" : {
         "active" : true
      },
      "include_op" : "OR"
   },
   "meta" : {
      "status" : "ok"
   }
}
```

**Comment by furiouslyalex** [comment]
This error is still happening on 2 apps we've updated to 1.6.1 for deals/media migration.

Bulk_api and pmp_contextual_assigner.

Current solution is to add a try/except around the content type check in connection.py in a local version of t1-python.

Fotios thinks this simple solution might work:
"well i can probably have some code to handle an empty response." 

Thanks,
Alex

**Comment by conoverm** [comment]
I think it's most likely the case this error occurs when the API returns some sort of non-formatted error response like an NGINX HTML error page. I've seen that often. Hopefully, all it needs an error catch on responses.

**Comment by FodT** [comment]
@conoverm @furiouslyalex Looking at the response handling, I'm not sure what would be more 'valid' behaviour outside of throwing a `T1Error` instead of a `ClientError` (which should only be thrown on actual improper SDK usage).

The fact nginx is returning 400 responses on actual valid responses is a separate issue which we shouldn't be trying to work around on the SDK.

**Comment by conoverm** [comment]
Understood. It does make the issue easier to diagnose. What do you think Alex?

**Comment by FodT** [comment]
Agreed, I missed the case where the content type is missing.

**Comment by furiouslyalex** [comment]
fyi @FodT  I tested the branch you PR's from your fork and it fixes my content type problem.  Thanks.
