### ISSUE TITLE
strategy.save() occasionally returns ParseError

### ISSUE THREAD

**Issue by zachliu** [MediaMath/t1-python#138]
'strategy.save()'. Error Type -> ClientError: "Could not parse XML response: ParseError('syntax error: line 1, column 0',)"

This is one of our old processes that is still using terminalone v1.0.5.
But I guess this error has little to do with the old version.

**Comment by FodT** [comment]
hey @zachliu , the xml parser has been updated in recent releases. Can you try to migrate to a newer release?
