### ISSUE TITLE
Support for budget flights

### ISSUE THREAD

**Issue by aidanhanneyti** [MediaMath/t1-python#171]
The library should support budget flights, as described in the API documentation:
https://mediamath.api-docs.io/v2/campaigns/budget-flights

**Comment by fsargent** [comment]
@FodT Let's work on this together when you're back. 
@michaelwelles We'll put this at the top on the backlog.

**Comment by masajame7** [comment]
I agree.

**Comment by fsargent** [comment]
This has been resolved in  #173
