### ISSUE TITLE
XMLParser fails because of missing '<entity></entity>' in XML response

### ISSUE THREAD

**Issue by zachliu** [MediaMath/t1-python#89]
For example, the xml response of this endpoint has no "\<entity>\</entity>"
```
POST $API_BASE/site_lists/$SITE_LIST_ID/domains
```
Hence, the following code works but return an error (AttributeError: 'XMLParser' object has no attribute 'entities')
```
from terminalone import T1
t1 = T1(USERNAME, PASSWORD, APIKEY, 'cookie')
t1._post('api/v2.0', rest='site_lists/10000/domains', data={'domains': 'abc.com'})
```

**Comment by pswaminathan** [comment]
Hi @zachliu , great question. I should first say that given that the post function is prefixed by an underscore, we can't guarantee its safe usage from update to update. Having said that, we have run into this with other similar situations. For instance, in [strategy.py](https://github.com/MediaMath/t1-python/blob/master/terminalone/models/strategy.py#L159-L166)<sup>1</sup>:

```python
    def save_domains(self, data):
        url = self._construct_url(addl=['domain_restrictions', ])
        # this endpoint doesn't return an entity like the supplies endpoint
        # so we ignore the error
        with suppress(AttributeError):
            entity, _ = super(Strategy, self)._post(PATHS['mgmt'], url, data)
```

We can add a similar method into the site list entity (or if you would like to submit it as a PR, we are happy to accept!); if you're in need of a workaround prior to that support, you can suppress the `AttributeError` similarly.

<sup>1</sup>`suppress` here is [built-in in Python 3.4](https://docs.python.org/3.5/library/contextlib.html#contextlib.suppress), but if you're using Python 2, you can see our implementation in [suppressed.py](https://github.com/MediaMath/t1-python/blob/master/terminalone/utils/suppressed.py).

**Comment by zachliu** [comment]
Hi @pswaminathan , thank you for the reply. I think I'm going to suppress the error for now.
