### ISSUE TITLE
Support for Bulk Edit

### ISSUE THREAD

**Issue by missinnale** [MediaMath/t1-python#93]
Looking for a way to save a collection of objects:

i.e. creating multiple concepts at the same time, without having to call `save()` on each one created. 

This would allow for things like saving multiple objects that have restrictions on being saved one at a time.

**Comment by FodT** [comment]
hey @missinnale, 

The way the API works, each entity would still have to be saved individually. You could write a utility function to loop over an array of newly created entities to save them - any functionality the SDK would provide would merely be syntactic sugar for this, so I feel it's probably better left to users to implement given their own unique use cases. 

We're looking into improvements in the adama APIs to allow for the creation of multiple entities at once; it's early days yet but watch this space :)
